### ISSUE TITLE
Xcode IBLayoutConstraint instance assertion

### ISSUE THREAD

**Issue by markst** [satroschenko/xibdump#1]
This works great! Thanks for the work. 

Occasionally the XIB will crash Xcode. 
Here is a snippet from the crash report, hope it helps.

```
ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEInterfaceBuilder/IDEInterfaceBuilder-14490.70/AutolayoutFoundation/Model/Constraints/IBLayoutConstraint.m:62
Details:  All objects in the constraints need to be instances of IBLayoutConstraint
Function: NSDictionary *_IBLayoutConstraintsOrConstraintRepresentationsKeyedByContainingView(__strong id<IBCollection>, __unsafe_unretained Class, BOOL)
```

**Comment by satroschenko** [comment]
Hi, 
Thank you for good feedback.

The program is under development and, sometimes it happens. 
Could you provide me a source nib file, that  I can fix it more quickly?

**Comment by satroschenko** [comment]
@markst Please, check this commit affc869 and let me know it helps or not.
